---
title: "Bank Marketing Case Study"
author: "Diego Pettorossi"
date: "1/31/2022"
output:
  html_document:
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(caret)
library(leaps)
library(aod)
library(ggplot2)
library(MASS)
library(randomForest)
library(C50)
library(rpart)
library(rpart.plot)
library(corrplot)
library(ggmosaic)
library(gmodels)
library(car)

bank_data <- read.csv("bank-additional.csv", header = TRUE, ";")

```

change pdays into intervals so that the 999 doesn't have as much impact

```{r}

bank_data$y <- factor(bank_data$y)
model1 <- glm(y ~., data = bank_data, family = "binomial")

summary(model1)

```


```{r}
summary(bank_data)
```


```{r}
CrossTable(bank_data$y)
```

```{r}
bank_data <- bank_data %>%
  mutate(y_binary = ifelse(y == "no",0,1))
```

```{r}
hist(bank_data$y_binary)
```

```{r}
colSums(bank_data == "unknown")
```

```{r}
sum(bank_data == "unknown")
```

```{r}
bank_data %>% 
  summarise_all(list(~sum(. == "unknown"))) %>% 
  gather(key = "variable", value = "nr_unknown") %>% 
  arrange(-nr_unknown)
```

```{r}
bank_data %>% 
  ggplot() +
  aes(x = age) +
  geom_bar() +
  geom_vline(xintercept = c(30, 60), 
             col = "red",
             linetype = "dashed") +
  facet_grid(y ~ .,
             scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 100, 5))
```

```{r}
table(bank_data$job)

CrossTable(bank_data$job, bank_data$y)
```

```{r}
marriage_table <- table(bank_data$marital, bank_data$y)
marriage_tab <- as.data.frame(prop.table(marriage_table, 2))
colnames(marriage_tab) <-  c("marital", "y", "perc")

ggplot(data = marriage_tab, aes(x = marital, y = perc, fill = y)) + 
  geom_bar(stat = 'identity', position = 'dodge', alpha = 2/3) + 
  xlab("Marital")+
  ylab("Percent")
```

```{r}
CrossTable(bank_data$education, bank_data$y)
```

```{r}
CrossTable(bank_data$default, bank_data$y)
```

```{r}
CrossTable(bank_data$housing, bank_data$y)
```

```{r}
CrossTable(bank_data$housing, bank_data$y)

chisq.test(bank_data$housing, bank_data$y)

```

```{r}
CrossTable(bank_data$loan, bank_data$y)
```

```{r}
loan_table <- table(bank_data$loan, bank_data$y)
loan_tab <- as.data.frame(prop.table(loan_table, 2))
colnames(loan_tab) <-  c("loan", "y", "perc")

ggplot(data = loan_tab, aes(x = loan, y = perc, fill = y)) + 
  geom_bar(stat = 'identity', position = 'dodge', alpha = 2/3) + 
  xlab("loan")+
  ylab("Percent")

chisq.test(bank_data$loan, bank_data$y)

```

```{r}
CrossTable(bank_data$month, bank_data$y)

bank_data %>% 
  ggplot() +
  aes(x = month, y = ..count../nrow(bank_data), fill = y) +
  geom_bar() +
  ylab("relative frequency")

month_table <- table(bank_data$month, bank_data$y)
month_tab <- as.data.frame(prop.table(month_table, 2))
colnames(month_tab) <-  c("month", "y", "perc")

ggplot(data = month_tab, aes(x = month, y = perc, fill = y)) + 
  geom_bar(stat = 'identity', position = 'dodge', alpha = 2/3) + 
  xlab("Month")+
  ylab("Percent")
```

```{r}
CrossTable(bank_data$day_of_week, bank_data$y)

bank_data %>% 
  ggplot() +
  aes(x = day_of_week, y = ..count../nrow(bank_data), fill = y) +
  geom_bar() +
  ylab("relative frequency")
```

```{r}
bank_data %>% 
  ggplot() +
  aes(x = campaign) +
  geom_bar() +
  facet_grid(y ~ .,
             scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 50, 5))
```

```{r}
bank_data <- bank_data %>%   
    filter(campaign <= 10) 

bank_data %>% 
  ggplot() +
  aes(x = campaign) +
  geom_bar() +
  facet_grid(y ~ .,
             scales = "free_y") +
  scale_x_continuous(breaks = seq(0, 10, 1))
```

```{r}
CrossTable(bank_data$campaign, bank_data$y)
```

```{r}
bank_data <- bank_data %>% 
  mutate(pdays_dummy = if_else(pdays == 999, "0", "1"))

CrossTable(bank_data$pdays_dummy, bank_data$y)
```

```{r}
bank_data <- bank_data %>% 
  mutate(previous_binned = if_else(previous >=  2, "2+", if_else(previous == 1, "1", "0")))

CrossTable(bank_data$previous_binned, bank_data$y)
```

```{r}
bank_data = bank_data %>% 
  mutate(age_discrete = if_else(age > 60, "high", if_else(age > 30, "mid", "low")))
```

```{r}
dup_bank_data <- bank_data

dup_bank_data <- dup_bank_data %>% 
  filter(job != "unknown")

dup_bank_data <- dup_bank_data %>% 
  filter(marital != "unknown")

dup_bank_data = dup_bank_data %>% 
  mutate(education = recode(education, "unknown" = "university.degree"))

dup_bank_data$contact <- factor(dup_bank_data$contact, order = TRUE, levels =c('telephone', 'cellular'))
dup_bank_data$education <- factor(dup_bank_data$education, order = TRUE, levels =c('illiterate','basic.4y', 'basic.6y','basic.9y', 'high.school','professional.course','university.degree'))
dup_bank_data$age_discrete <- factor(dup_bank_data$age_discrete, order = TRUE, levels =c('low', 'mid','high'))
dup_bank_data$job <- factor(dup_bank_data$job, order = TRUE, levels =c('blue-collar', 'services','entrepreneur', 'housemaid', 'self-employed','technician', 'management','admin.','unemployed', 'retired','student'))
dup_bank_data$marital <- factor(dup_bank_data$marital, order = TRUE, levels =c('married', 'divorced', 'single'))
dup_bank_data$month <- factor(dup_bank_data$month, order = TRUE, levels =c('mar', 'apr','may', 'jun','jul', 'aug', 'sep','oct', 'nov','dec'))
dup_bank_data$previous_binned <- factor(dup_bank_data$previous_binned, order = TRUE, levels =c('0', '1','2+'))
dup_bank_data$poutcome <- factor(dup_bank_data$poutcome, order = TRUE, levels =c('nonexistent', 'failure','success'))
```

```{r}
set.seed(1984)
training <- createDataPartition(dup_bank_data$y_binary, p = 0.8, list=FALSE)

train_data <- dup_bank_data[training,]
test_data <- dup_bank_data[-training,]
```


```{r}
cor(train_data[sapply(train_data, is.numeric)])
```


```{r}
model <- glm(y_binary ~ age_discrete + job + marital + education + contact + month + pdays_dummy + previous_binned + poutcome + cons.price.idx + cons.conf.idx + nr.employed,family=binomial(link='logit'),data=train_data)

summary(model)
```

```{r}
model_2 <- glm(y_binary ~ age_discrete + marital + education + contact + month + pdays_dummy + previous_binned + poutcome,family=binomial(link='logit'),data=train_data)

summary(model_2)
```

```{r}
model_3 <- glm(y_binary ~ age_discrete + marital + education + contact + month + pdays_dummy + previous_binned + poutcome,family=binomial(link='logit'),data=train_data)

summary(model_3)
```

```



```{r}
anova(model,model_2,test = "Chisq")
```

```{r}
pred.train <- predict(model,test_data)

pred.train <- ifelse(pred.train > 0.5,1,0)
mean(pred.train == test_data$y_binary)


```

```{r}
t1 <- table(pred.train,test_data$y_binary)

# Presicion and recall of the model
presicion <- t1[1,1]/(sum(t1[1,]))
recall <- t1[1,1]/(sum(t1[,1]))
presicion
```

